apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::242485614316:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::242485614316:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-LWQ6U2NG2X3P
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-03-22T21:37:56Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "873"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 648d4752-6c85-11ea-8d81-0ef2cdf7e862
